python3 -u run.py \
  --is_training 1 \
  --root_path dataset/dataset/stock \
  --data_path stock01.csv \
  --model_id stock0x \
  --model mamba \
  --data stock \
  --features M \
  --seq_len 30 \
  --label_len 0 \
  --pred_len 1 \
  --e_layers 5 \
  --d_layers 3 \
  --factor 3 \
  --enc_in 4 \
  --dec_in 4 \
  --c_out 4 \
  --gpu 0 \
  --des Exp_stock0x \
  --p_hidden_dims 128 128 128 \
  --p_hidden_layers 3 \
  --itr 1 \
  --train_epochs 1 &

